#!/usr/bin/env node

/**
 * Environment Variable Generator for Netlify Production Builds
 * 
 * This script generates an env.js file that exposes environment variables
 * to the browser context for production deployments where process.env is not available.
 * 
 * Usage:
 * - npm run generate:env (generates env.js from environment variables)
 * - Called automatically during npm run build:netlify
 */

const fs = require('fs');
const path = require('path');
// Load local .env for development so Option B works without manual shell exports
try {
  require('dotenv').config({ path: path.join(__dirname, '..', '.env') });
  // eslint-disable-next-line no-console
  console.log('🔎 Loaded .env from project root for env.js generation');
} catch (e) {
  // eslint-disable-next-line no-console
  console.log('ℹ️ dotenv not loaded or .env missing (this is fine on Netlify)');
}

// Environment variables that should be exposed to the browser
const ENV_VARS = [
    'VITE_SUPABASE_URL',
    'VITE_SUPABASE_ANON_KEY',
    'VITE_SUPABASE_SERVICE_ROLE_KEY',
    'VITE_GOOGLE_GEMINI_API_KEY',
    'VITE_GOOGLE_CLIENT_ID',
    'VITE_GOOGLE_CLIENT_SECRET',
    'NODE_ENV'
];

// Fallback values (do NOT include secrets)
const FALLBACKS = {
    'NODE_ENV': 'production'
};

function generateEnvFile() {
    console.log('🔄 Generating environment variables for browser...');
    
    const env = {};
    let hasAnyKey = false;
    
    // Collect environment variables
    ENV_VARS.forEach(key => {
        const value = process.env[key];
        if (value) {
            env[key] = value;
            hasAnyKey = true;
            console.log(`✅ Found ${key}: ${key.includes('KEY') ? '[REDACTED]' : ('' + value).slice(0, 30) + (("" + value).length > 30 ? '...' : '')}`);
        } else if (Object.prototype.hasOwnProperty.call(FALLBACKS, key)) {
            env[key] = FALLBACKS[key];
            console.log(`ℹ️  Using default for ${key}: ${FALLBACKS[key]}`);
        } else {
            console.log(`❌ Missing ${key}`);
        }
    });
    
    if (!hasAnyKey) {
        console.warn('⚠️  No environment variables found. Make sure to set them in Netlify dashboard.');
    }
    
    // Generate the JavaScript content
    const jsContent = `// Auto-generated environment variables for browser context
// Generated at: ${new Date().toISOString()}
// DO NOT EDIT THIS FILE MANUALLY

(function() {
    'use strict';
    
    // Environment variables injected at build time
    window.__ENV__ = ${JSON.stringify(env, null, 2)};
    
    // Backwards-compat: expose alias without trailing underscore used by legacy pages
    window.__ENV = window.__ENV__;
    
    // Legacy compatibility: expose non-Vite keys for static test pages
    window.ENV = {
      SUPABASE_URL: window.__ENV__.VITE_SUPABASE_URL,
      SUPABASE_ANON_KEY: window.__ENV__.VITE_SUPABASE_ANON_KEY,
      SUPABASE_SERVICE_ROLE_KEY: window.__ENV__.VITE_SUPABASE_SERVICE_ROLE_KEY
    };
    // Also set global shims expected by older diagnostics
    window.supabaseUrl = window.ENV.SUPABASE_URL;
    window.supabaseAnonKey = window.ENV.SUPABASE_ANON_KEY;
    window.supabaseServiceRoleKey = window.ENV.SUPABASE_SERVICE_ROLE_KEY;
    // Helper function to get environment variables with fallbacks
    window.getEnv = function(key, fallback = null) {
        return (window.__ENV__ && window.__ENV__[key] != null) ? window.__ENV__[key] : fallback;
    };
    
    // Log environment status (without exposing sensitive data)
    console.log('🌍 Environment variables loaded:', {
        hasSupabaseUrl: Boolean(window.__ENV__.VITE_SUPABASE_URL),
        hasSupabaseKey: Boolean(window.__ENV__.VITE_SUPABASE_ANON_KEY),
        hasGeminiKey: Boolean(window.__ENV__.VITE_GOOGLE_GEMINI_API_KEY),
        nodeEnv: window.__ENV__.NODE_ENV || 'development'
    });
    
})();
`;
    
    // Write to public directory for static serving
    const outputPath = path.join(__dirname, '..', 'public', 'env.js');
    
    try {
        fs.mkdirSync(path.dirname(outputPath), { recursive: true });
        fs.writeFileSync(outputPath, jsContent, 'utf8');
        console.log(`✅ Environment file generated: ${outputPath}`);
        console.log(`📦 File size: ${(jsContent.length / 1024).toFixed(2)} KB`);
        
        // Also write to dist directory if it exists (for immediate testing)
        const distPath = path.join(__dirname, '..', 'dist', 'env.js');
        const distDir = path.dirname(distPath);
        if (fs.existsSync(distDir)) {
            fs.writeFileSync(distPath, jsContent, 'utf8');
            console.log(`✅ Also copied to dist: ${distPath}`);
        }
        
    } catch (error) {
        console.error('❌ Failed to write environment file:', error);
        process.exit(1);
    }
}

// Export for programmatic use
module.exports = { generateEnvFile, ENV_VARS, FALLBACKS };

// Run if called directly
if (require.main === module) {
    generateEnvFile();
}